In [15]:
from google.colab import drive
import pandas as pd
import numpy as np
# Mount Google Drive
drive.mount('/content/drive')

# Read the CSV file from Google Drive
purchase_df = pd.read_csv('/content/drive/My Drive/car_purchase.csv')
print(purchase_df)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
        User ID  Gender   Age  Estimated Salary  Purchased  Unnamed: 5
0    15624510.0    Male  19.0           19000.0        0.0         NaN
1    15623944.0    Male  35.0           20000.0        0.0         NaN
2    15623378.0  Female  26.0           43000.0        0.0         NaN
3    15622812.0  Female  27.0           57000.0        0.0         NaN
4    15622246.0    Male  19.0           76000.0        0.0         NaN
..          ...     ...   ...               ...        ...         ...
110         NaN     NaN   NaN               NaN        NaN         NaN
111         NaN     NaN   NaN               NaN        NaN         NaN
112         NaN     NaN   NaN               NaN        NaN         NaN
113         NaN     NaN   NaN               NaN        NaN         NaN
114         NaN     NaN   NaN               NaN        NaN         NaN

[115 rows x 6 colu

In [16]:
purchase_df.head(10)

User ID  Gender   Age  Estimated Salary  Purchased  Unnamed: 5
0  15624510.0    Male  19.0           19000.0        0.0         NaN
1  15623944.0    Male  35.0           20000.0        0.0         NaN
2  15623378.0  Female  26.0           43000.0        0.0         NaN
3  15622812.0  Female  27.0           57000.0        0.0         NaN
4  15622246.0    Male  19.0           76000.0        0.0         NaN
5  15621680.0    Male  27.0           58000.0        0.0         NaN
6  15621114.0  Female  27.0           84000.0        0.0         NaN
7  15620548.0  Female  32.0          150000.0        1.0         NaN
8  15619982.0    Male  25.0           33000.0        0.0         NaN
9  15619416.0  Female  35.0           65000.0        0.0         NaN

In [17]:
purchase_df.tail(10)

User ID Gender  Age  Estimated Salary  Purchased  Unnamed: 5
105      NaN    NaN  NaN               NaN        NaN         NaN
106      NaN    NaN  NaN               NaN        NaN         NaN
107      NaN    NaN  NaN               NaN        NaN         NaN
108      NaN    NaN  NaN               NaN        NaN         NaN
109      NaN    NaN  NaN               NaN        NaN         NaN
110      NaN    NaN  NaN               NaN        NaN         NaN
111      NaN    NaN  NaN               NaN        NaN         NaN
112      NaN    NaN  NaN               NaN        NaN         NaN
113      NaN    NaN  NaN               NaN        NaN         NaN
114      NaN    NaN  NaN               NaN        NaN         NaN

In [18]:
purchase_df.drop(purchase_df.tail(15).index,inplace=True)
purchase_df.tail(10)


User ID  Gender   Age  Estimated Salary  Purchased  Unnamed: 5
90  15452018.0    Male  42.0           29000.0        0.0         NaN
91  15275532.0    Male  27.0           33000.0        0.0         NaN
92  15099046.0  Female  35.0           34000.0        0.0         NaN
93  14922560.0  Female  34.0           41000.0        0.0         NaN
94  14746074.0  Female  32.0           38000.0        1.0         NaN
95  14569588.0    Male  31.0           45000.0        1.0         NaN
96  14393102.0    Male  41.0           41000.0        0.0         NaN
97  14216616.0    Male  51.0           50000.0        0.0         NaN
98  14040130.0    Male  28.0           28000.0        0.0         NaN
99  13863644.0    Male  26.0           34000.0        1.0         NaN

In [21]:
purchase_df.head()


User ID  Gender   Age  Estimated Salary  Purchased  Unnamed: 5
0  15624510.0    Male  19.0           19000.0        0.0         NaN
1  15623944.0    Male  35.0           20000.0        0.0         NaN
2  15623378.0  Female  26.0           43000.0        0.0         NaN
3  15622812.0  Female  27.0           57000.0        0.0         NaN
4  15622246.0    Male  19.0           76000.0        0.0         NaN

In [13]:
purchase_df.tail()

User ID  Gender   Age  Estimated Salary  Purchased  Unnamed: 5
65  15008157.0  Female  26.0           46000.0        1.0         NaN
66  15607512.0  Female  42.0           41000.0        1.0         NaN
67  16206867.0  Female  35.0           19000.0        0.0         NaN
68  16806222.0    Male  26.0           75000.0        0.0         NaN
69  17405577.0  Female  27.0           56000.0        1.0         NaN

In [22]:
x= purchase_df.iloc[:,[2,3]].values
y= purchase_df.iloc[:,[4]].values
print(x)
print(y)

[[1.9e+01 1.9e+04]
 [3.5e+01 2.0e+04]
 [2.6e+01 4.3e+04]
 [2.7e+01 5.7e+04]
 [1.9e+01 7.6e+04]
 [2.7e+01 5.8e+04]
 [2.7e+01 8.4e+04]
 [3.2e+01 1.5e+05]
 [2.5e+01 3.3e+04]
 [3.5e+01 6.5e+04]
 [2.6e+01 8.0e+04]
 [2.6e+01 5.2e+04]
 [2.0e+01 8.6e+04]
 [3.2e+01 1.8e+04]
 [1.8e+01 8.2e+04]
 [2.9e+01 8.0e+04]
 [4.7e+01 2.5e+04]
 [4.5e+01 2.6e+04]
 [4.6e+01 2.8e+04]
 [4.8e+01 2.9e+04]
 [4.5e+01 2.2e+04]
 [4.7e+01 4.9e+04]
 [3.2e+01 2.0e+04]
 [2.5e+01 4.0e+04]
 [3.5e+01 2.2e+04]
 [2.6e+01 5.5e+04]
 [2.6e+01 4.8e+04]
 [2.0e+01 4.2e+04]
 [3.2e+01 3.6e+04]
 [1.8e+01 2.2e+04]
 [2.9e+01 5.2e+04]
 [4.7e+01 6.1e+04]
 [2.0e+01 2.3e+04]
 [3.0e+01 4.5e+04]
 [4.0e+01 4.6e+04]
 [2.5e+01 5.0e+04]
 [3.5e+01 2.8e+04]
 [4.5e+01 5.9e+04]
 [2.2e+01 2.5e+04]
 [4.2e+01 4.6e+04]
 [3.2e+01 4.0e+04]
 [3.8e+01 2.8e+04]
 [4.8e+01 5.2e+04]
 [5.0e+01 5.1e+04]
 [4.9e+01 4.3e+04]
 [5.5e+01 6.8e+04]
 [2.6e+01 3.5e+04]
 [3.8e+01 3.8e+04]
 [2.3e+01 4.0e+04]
 [2.7e+01 4.2e+04]
 [4.1e+01 3.9e+04]
 [5.3e+01 4.9e+04]
 [2.6e+01 3.

In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[2.3e+01 4.0e+04]
 [2.7e+01 8.4e+04]
 [2.6e+01 3.4e+04]
 [3.5e+01 3.8e+04]
 [4.0e+01 1.2e+05]
 [3.8e+01 4.2e+04]
 [2.8e+01 4.7e+04]
 [4.2e+01 2.9e+04]
 [2.6e+01 7.5e+04]
 [5.3e+01 4.9e+04]
 [2.0e+01 4.2e+04]
 [4.6e+01 2.8e+04]
 [2.7e+01 3.1e+04]
 [4.1e+01 4.1e+04]
 [2.8e+01 5.0e+04]
 [3.5e+01 2.0e+04]
 [2.3e+01 2.5e+04]
 [4.8e+01 5.2e+04]
 [3.8e+01 2.8e+04]
 [1.9e+01 7.6e+04]
 [2.9e+01 8.0e+04]
 [4.5e+01 2.6e+04]
 [3.2e+01 4.0e+04]
 [2.2e+01 2.5e+04]
 [2.7e+01 5.8e+04]
 [2.7e+01 3.3e+04]
 [2.6e+01 4.7e+04]
 [1.9e+01 1.9e+04]
 [4.0e+01 4.6e+04]
 [3.2e+01 3.6e+04]
 [4.1e+01 3.9e+04]
 [2.6e+01 5.2e+04]
 [2.5e+01 5.0e+04]
 [2.5e+01 4.0e+04]
 [2.6e+01 3.3e+04]
 [2.6e+01 8.0e+04]
 [4.7e+01 6.1e+04]
 [4.2e+01 4.1e+04]
 [2.9e+01 3.9e+04]
 [3.9e+01 5.8e+04]
 [3.1e+01 3.5e+04]
 [2.0e+01 2.3e+04]
 [3.2e+01 2.5e+04]
 [1.8e+01 8.2e+04]
 [2.6e+01 4.0e+04]
 [4.8e+01 2.9e+04]
 [1.8e+01 2.2e+04]
 [2.7e+01 4.2e+04]
 [5.1e+01 5.0e+04]
 [2.8e+01 2.8e+04]
 [2.7e+01 5.6e+04]
 [4.5e+01 2.2e+04]
 [3.2e+01 3.

In [26]:
from sklearn.preprocessing import StandardScaler
st_x= StandardScaler()
x_train= st_x.fit_transform(x_train)
x_test= st_x.transform(x_test)

In [27]:
print(x_train)
print(x_test)

[[-1.06445219 -0.25965156]
 [-0.65026846  2.12711767]
 [-0.75381439 -0.58512009]
 [ 0.17809901 -0.36814107]
 [ 0.69582867  4.07992886]
 [ 0.48873681 -0.15116205]
 [-0.54672253  0.12006173]
 [ 0.90292054 -0.85634387]
 [-0.75381439  1.63891487]
 [ 2.04192581  0.22855124]
 [-1.37508999 -0.15116205]
 [ 1.31710427 -0.91058863]
 [-0.65026846 -0.74785436]
 [ 0.79937461 -0.20540681]
 [-0.54672253  0.28279599]
 [ 0.17809901 -1.34454667]
 [-1.06445219 -1.07332289]
 [ 1.52419614  0.3912855 ]
 [ 0.48873681 -0.91058863]
 [-1.47863593  1.69315963]
 [-0.44317659  1.91013865]
 [ 1.21355834 -1.01907814]
 [-0.13253879 -0.25965156]
 [-1.16799813 -1.07332289]
 [-0.65026846  0.71675403]
 [-0.65026846 -0.63936485]
 [-0.75381439  0.12006173]
 [-1.47863593 -1.39879142]
 [ 0.69582867  0.06581697]
 [-0.13253879 -0.47663058]
 [ 0.79937461 -0.31389632]
 [-0.75381439  0.3912855 ]
 [-0.85736033  0.28279599]
 [-0.85736033 -0.25965156]
 [-0.75381439 -0.63936485]
 [-0.75381439  1.91013865]
 [ 1.42065021  0.8794883 ]
 

In [28]:
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )
classifier.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [30]:
y_pred= classifier.predict(x_test)
print(y_pred)

[1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 1.
 0.]


In [31]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
print(cm)

[[11  7]
 [ 4  3]]


In [32]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
print(cm)

[[11  7]
 [ 4  3]]
